<?php
/**
 * @file
 * 
 * 
 *
 * @author Kálmán Hosszu - hosszu.kalman@gmail.com
 */
 
/* ====================== */
/* ==== DRUPAL HOOKS ==== */
/* ====================== */

/**
 * Implementation of hook_menu().
 *
 * @return An array of menu items.
 */
function mg_picker_menu() {
  $items = array();

  $items['mg_picker/autocomplete'] = array(
    'title' => 'Media Gallery picker autocomplete',
    'description' => 'Form automplete callback, to get galleries.',
    'page callback' => 'pg_picker_gallery_autocomplete',
    'access callback' => 'media_access',
    'access arguments' => array('view'),
  );
  
  return $items;
}

/**
 * Implements hook_filter_info().
 */
function mg_picker_filter_info() {
  $filters = array();
  
  $filters['mg_picker'] = array(
    'title' => t('Media galleries'),
    'description' => t('Converts media galleries to a link.'),
    'process callback' => 'mg_picker_filter',
    'tips callback' => 'mg_picker_filter_tips', // @TODO not implemented
  );

  // If the WYSIWYG module is enabled, add additional help.
  if (module_exists('wysiwyg')) {
    $filters['mg_picker']['description'] .= ' ' . t('This must be enabled for the WYSIWYG integration to work correctly with this text filter.');
  }

  return $filters;
}

/* ====================== */
/* == MODULE FUNCTIONS == */
/* ====================== */

/**
 * Build mg_picker_gallery_search_form form.
 * 
 * @param array $form_state
 * @return
 *   The created form. 
 */
function mg_picker_gallery_search_form($form_state) {
  $form = array();

  $form['gallery_nid'] = array(
    '#type' => 'textfield',
    '#title' => t('Gallery'),
    '#description' => t('Type the title of the gallery, and the module will suggest the possibilities.'),
    '#autocomplete_path' => 'mg_picker/autocomplete',
  );
  
  $form['gallery_nid_submit'] = array(
    '#type' => 'submit',
    '#value' => t('OK'),
    '#ajax' => array(
      'callback' => 'mg_picker_get_images',
      'wrapper' => 'gallery-images',
      'effect' => 'fade',
    ),
  );
  
  // Container for just the gallery images.
  $form['gallery_image_wrapper'] = array(
    '#prefix' => '<div id="gallery-images">',
    '#suffix' => '</div>',
  );

  return $form;
}

/**
 * Autocomplete maches to finding galleries.
 *
 * @param array $string 
 */
function pg_picker_gallery_autocomplete($string) {
  $matches = array();
  
  if ($string) {
    $result = db_select('node')
        ->fields('node', array('nid', 'title'))
        ->condition('title', '%' . db_like($string) . '%', 'LIKE')
        ->condition('type', 'media_gallery')
        ->range(0, 10)->execute();
    foreach ($result as $node) {
      $matches[$node->nid] = check_plain($node->title);
    }
  }

  drupal_json_output($matches);
}

function mg_picker_get_images($form, $form_state) {
  $out = '';
  
  $node = node_load($form_state['values']['gallery_nid']);
  
  if ($node->type == 'media_gallery') {
    $files = file_load_multiple(media_gallery_get_file_ids($node));
    
    // This is shit, use medi module's funcions. I need a list function what generates the html and attach JS.
    foreach ($files as $file) {
//      $elements = array(
//        '#theme' => 'media_thumbnail',
//        '#file' => $file,
//      );
//      $out .= drupal_render($elements);
    }
    
  }
  return $out;
}